[package]
name = "rust-ml"
version = "0.1.1"
authors = ["Tom Selfin <selfint@gmail.com>"]
edition = "2018"

[dependencies]
ndarray = "0.14.0"
ndarray-rand = "0.13.0"
ndarray-stats = "0.4.0"

[dev-dependencies]
csv = "1.1"

